site_name: Zebrunner CE

theme:
  name: material
  palette:
    scheme: zebrunner
  logo: assets/logo.svg
  favicon: assets/favicon.svg
repo_url: https://github.com/zebrunner/community-edition
repo_name: community-edition

markdown_extensions:
  - attr_list
  - md_in_html

copyright: 2022 Zebrunner, Inc. All Rights Reserved
extra:
  homepage: https://zebrunner.com
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/zebrunner
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/company/zebrunner
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/zebrunner
    - icon: fontawesome/brands/telegram 
      link: https://t.me/zebrunner

extra_css:
  - stylesheets/extra.css

nav:
    - Overview: index.md
    - Prerequisites: prerequisites.md
    - Installation Guide: install-guide.md
    - Configuration Guide: config-guide.md
    - User Guide: user-guide.md
    - Integration:
      - Source Code Manager: integration/scm.md
      - SonarQube: integration/sonarqube.md
      - S3 Storage: integration/aws-s3.md